### ISSUE TITLE
Value suffixes and units

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#6]
Some values require formatting of the raw data before being displayed. Currently, these are memory capacity (KiB, MiB, etc.), Clock Speed (kHz, MHz), and Total Dose (k, M).

There are also multiple points requiring units in the header:

- Voltage (V)
- Total Dose (Rad)
- Latch-Up Threshold (MeV-cm2/mg)

**Comment by jboullion** [comment]
@codeflight1 for Memory capacity, speed, and total dose can I assume all of these are currently stored in their base units? Byte, Hz, Rad?

**Comment by codeflight1** [comment]
That should be correct.

**Comment by jboullion** [comment]
@codeflight1 I updated this so the main table will format things as expected, however I did not apply this change to the Latch-up Threshold...because I don't know how / if the values in the DB are set up for abbreviation.

Most seem to be "Immune", but some I see say something like ">80 MeV.cm2/mg". Should we be abbreviating this and if so how?

[Commit](https://github.com/jboullion/rad-toolkit/commit/f1d691e25faf00569bf36074fc12ef33075d4472)

**Comment by jboullion** [comment]
Note to self, still need to update the filters with abbreviations

**Comment by codeflight1** [comment]
Oh yeah, Latch-up threshold shouldn't need suffixes.

**Comment by codeflight1** [comment]
It appears that clock speed is only having a suffix added under the memory category, and not under microprocessors.

EDIT: This was because the values were strings, should be fixed now.

**Comment by jboullion** [comment]
Suffixes updated and applied to all component properties. Should also fix the filters not working.

[Commit](https://github.com/jboullion/rad-toolkit/commit/1343c2884fabc6203fd0ee71b522c58c443c4f9b)

This commit did break the interfaces component table display. Will work on that next.

**Comment by codeflight1** [comment]
LGTM
