### ISSUE TITLE
Feature Request: Update filter options when filters are applied

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#9]
I think the best way to implement this is to disable the options for items that have been hidden by other options.

**Comment by jboullion** [comment]
So I am a little torn about this one since it could make things...weird. Still, I think I found a fairly simple way to do this so I implemented it and it seems to work in my limited testing.

Let me know what you think.

[Commit](https://github.com/jboullion/rad-toolkit/commit/d39b81427f13a6c6a81aa14415d91c88eb7c4171)

**Comment by codeflight1** [comment]
LGTM

If we think of a better way to do this later we can implement it then.
